from models import Base, engine, SessionLocal, Question

SEED = {'Diversos': [('O que está na imagem?',
               'Pirâmides de Queóps',
               'Pirâmides de Gizé',
               'Pirâmides de Quéfren',
               'Pirâmides de Miquerinos',
               'B',
               'images/piramides.jpg'),
              ('Qual invenção está na imagem (popularizada por Edison)?',
               'Eletricidade',
               'Lâmpada elétrica',
               'Fotografia',
               'Primeiro aparelho elétrico',
               'B',
               'images/invencao-edison.jpg'),
              ('Qual bandeira (cruz azul sobre fundo amarelo) aparece?',
               'Noruega',
               'Suécia',
               'Islândia',
               'Finlândia',
               'B',
               'images/bandeira.jpg'),
              ("Qual é este ponto turístico?", "Taj Mahal", "Angkor Wat", "Sagrada Família", "Burj Khalifa", "A", "images/ponto-turistico.jpg"),
              ("Qual é este animal?", "Búfalo", "Bisão", "Alce", "Iaque", "B", "images/animal.jpg"),
              ("Qual destas bebidas é tradicionalmente fermentada de arroz?", "Saké", "Tequila", "Vodca", "Gin", "A", None),
              ('Qual é o maior planeta do Sistema Solar?',
               'Saturno',
               'Júpiter',
               'Urano',
               'Netuno',
               'B',
               None),
              ('Qual animal dorme de cabeça para baixo?',
               'Morcego',
               'Bicho-preguiça',
               'Coruja',
               'Gato',
               'A',
               None),
              ('Qual é a capital da Islândia?',
               'Oslo',
               'Reykjavik',
               'Estocolmo',
               'Helsinque',
               'B',
               None),
              ('Qual é o metal líquido à temperatura ambiente?',
               'Gálio',
               'Sódio',
               'Césio',
               'Mercúrio',
               'D',
               None),
              ("Qual país é conhecido como 'Terra do Sol Nascente'?",
               'China',
               'Japão',
               'Coreia do Sul',
               'Vietnã',
               'B',
               None),
              ('Qual oceano é o maior em área?',
               'Atlântico',
               'Pacífico',
               'Índico',
               'Ártico',
               'B',
               None),
              ('Qual cidade é famosa pelo Cristo Redentor?',
               'Lisboa',
               'Rio de Janeiro',
               'Buenos Aires',
               'São Paulo',
               'B',
               None),
              ('Qual é a unidade básica da vida?',
               'Átomo',
               'Célula',
               'Molécula',
               'Tecido',
               'B',
               None),
              ('Qual gás é essencial para a respiração humana?',
               'Nitrogênio',
               'Gás Carbônico',
               'Hélio',
               'Oxigênio',
               'D',
               None),
              ('Qual país tem mais vulcões ativos?',
               'Indonésia',
               'Japão',
               'Islândia',
               'Itália',
               'A',
               None),
              ('Qual deserto é o maior (não polar)?',
               'Saara',
               'Kalahari',
               'Gobi',
               'Atacama',
               'A',
               None),
              ('Qual instrumento mede a pressão atmosférica?',
               'Barômetro',
               'Termômetro',
               'Higrômetro',
               'Anemômetro',
               'A',
               None),
              ('Qual é o principal gás do efeito estufa dos fósseis?',
               'O₂',
               'N₂',
               'CH₄',
               'CO₂',
               'D',
               None),
              ("Quem pintou 'A Noite Estrelada'?",
               'Van Gogh',
               'Monet',
               'Picasso',
               'Dalí',
               'A',
               None),
              ('Qual país venceu a Copa do Mundo feminina de 2019?',
               'Estados Unidos',
               'Holanda',
               'Alemanha',
               'Inglaterra',
               'A',
               None),
              ('Qual idioma é mais falado como nativo?',
               'Inglês',
               'Hindi',
               'Espanhol',
               'Mandarim',
               'D',
               None),
              ("Qual cidade é conhecida como 'A Cidade Luz'?",
               'Londres',
               'Roma',
               'Berlim',
               'Paris',
               'D',
               None),
              ('Qual é o símbolo químico da água?', 'H2', 'O2', 'CO2', 'H2O', 'D', None),
              ('Qual montanha é a mais alta do mundo?',
               'K2',
               'Kangchenjunga',
               'Lhotse',
               'Everest',
               'D',
               None),
              ('Qual continente tem o maior número de países?',
               'Ásia',
               'Europa',
               'África',
               'América',
               'C',
               None),
              ("Qual escritor criou 'Dom Quixote'?",
               'Victor Hugo',
               'Goethe',
               'Shakespeare',
               'Miguel de Cervantes',
               'D',
               None),
              ('Qual é o instrumento usado para medir temperatura?',
               'Higrômetro',
               'Barômetro',
               'Termômetro',
               'Anemômetro',
               'C',
               None),
              ('Qual é o símbolo químico do ouro?', 'Ag', 'Fe', 'Au', 'Cu', 'C', None),
              ('Qual cidade abriga o Coliseu?',
               'Atenas',
               'Istambul',
               'Roma',
               'Florença',
               'C',
               None),
              ('Qual é a moeda do Japão?', 'Yuan', 'Won', 'Iene (Yen)', 'Baht', 'C', None),
              ('Qual país tem a cidade de Marrakech?',
               'Egito',
               'Tunísia',
               'Marrocos',
               'Argélia',
               'C',
               None),
              ('Qual é o menor país do mundo?',
               'Mônaco',
               'San Marino',
               'Vaticano',
               'Liechtenstein',
               'C',
               None),
               ("Qual destes NÃO é um continente?", "Oceania", "Antártica", "Eurásia", "África", "C", None),
               ("Qual destes animais é um monotremo?", "Ornitorrinco", "Golfinho", "Lontra", "Texugo", "A", None),
               ("Qual cidade é famosa pelos canais e pontes (Europa do Leste)?", "Bruges", "Veneza", "Amsterdã", "São Petersburgo", "D", None),
               ("Qual desses países é conhecido por castelos medievais bem preservados, como Bran?", "Romênia", "Bulgária", "Sérvia", "Eslováquia", "A", None),
               ("Qual país abriga o Monte Kilimanjaro?", "Quênia", "Etiópia", "Tanzânia", "Uganda", "C", None),
               ("Qual instrumento mede a umidade relativa do ar?", "Higrômetro", "Barômetro", "Termômetro", "Altímetro", "A", None),
               ("Qual mar banha Israel e Jordânia e tem alta salinidade?", "Morto", "Vermelho", "Negro", "Cáspio", "A", None),
               ("Qual destas línguas usa predominantemente o alfabeto cirílico?", "Polonês", "Tcheco", "Sérvio (variante)", "Húngaro", "C", None),
               ("Qual país tem a cidade de Dubrovnik?", "Croácia", "Eslovênia", "Bósnia", "Sérvia", "A", None),
               ("Qual destas é uma estrela?", "Vênus", "Júpiter", "Sol", "Lua", "C", None),
               ("Qual destas cozinhas é famosa pelo kimchi?", "Japonesa", "Chinesa", "Coreana", "Tailandesa", "C", None),
               ("Qual destas obras é de Da Vinci?", "Guernica", "O Grito", "A Última Ceia", "As Meninas", "C", None),
               ("Qual destas cidades NÃO é capital?", "Berlim", "Sydney", "Roma", "Lisboa", "B", None),
               ("Qual país é famoso pelo Caminho de Santiago?", "Portugal", "Espanha", "Itália", "França", "B", None),
               ("Qual moeda é usada no México?", "Peso", "Dólar", "Euro", "Sol", "A", None),
               ("Qual destas festas é típica da cultura japonesa no verão?", "Hanami", "Carnaval", "Oktoberfest", "Obon", "D", None),
               ("Qual país é conhecido pelos fiordes e pela aurora boreal no norte?", "Noruega", "Dinamarca", "Suécia", "Finlândia", "A", None),
               ("Qual destas bebidas é tradicionalmente fermentada de arroz?", "Saké", "Tequila", "Vodca", "Gin", "A", None)],
 'Esportes': [('Quem é o atleta na imagem (multicampeão dos 100m e 200m)?',
               'Justin Gatlin',
               'Yohan Blake',
               'Asafa Powell',
               'Usain Bolt',
               'D',
               'images/corredor.jpg'),
              ('Qual piloto da F1 aparece na imagem?',
               'Lewis Hamilton',
               'Sebastian Vettel',
               'Fernando Alonso',
               'Nico Rosberg',
               'A',
               'images/piloto.jpg'),
              ('A taça sobre a grama na imagem é de qual torneio de Tênis?',
               'Roland Garros',
               'Australian Open',
               'Wimbledon',
               'US Open',
               'C',
               'images/trofeu.jpg'),
                ("Que bola é esta (esporte)?", "Rúgbi", "Beisebol", "Críquete", "Futebol americano", "A", "images/bola.jpeg"),
                ("De qual liga é este logotipo?", "NFL", "NBA", "NHL", "MLB", "B", "images/logo-liga.jpg"),
              ('Qual país sediou as Olimpíadas de 2008?',
               'Japão',
               'Brasil',
               'China',
               'Rússia',
               'C',
               None),
              ('Qual seleção venceu a primeira Copa do Mundo (1930)?',
               'Argentina',
               'Brasil',
               'Itália',
               'Uruguai',
               'D',
               None),
              ("Quem marcou o 'Gol da Mão de Deus' em 1986?",
               'Platini',
               'Maradona',
               'Lineker',
               'Zico',
               'B',
               None),
              ('Qual clube revelou Pelé para o mundo?',
               'Corinthians',
               'Santos',
               'Flamengo',
               'Vasco',
               'B',
               None),
              ('Qual é o torneio anual de clubes mais antigo do futebol?',
               'FA Cup',
               'Copa do Rei',
               'Taça de Portugal',
               'DFB-Pokal',
               'A',
               None),
              ('Qual seleção venceu a Copa do Mundo de 2010?',
               'Alemanha',
               'Espanha',
               'Holanda',
               'Uruguai',
               'B',
               None),
              ('Em qual cidade ocorre a maratona mais antiga em continuidade?',
               'Boston',
               'Londres',
               'Berlim',
               'Atenas',
               'A',
               None),
              ('Quem é o maior medalhista olímpico da história?',
               'Michael Phelps',
               'Usain Bolt',
               'Larisa Latynina',
               'Mark Spitz',
               'A',
               None),
              ("Qual tenista conquistou o 'Golden Slam' no mesmo ano?",
               'Serena Williams',
               'Steffi Graf',
               'Martina Navratilova',
               'Monica Seles',
               'B',
               None),
              ('Qual seleção masculina ganhou o primeiro ouro olímpico do vôlei brasileiro?',
               'Brasil (1992)',
               'Brasil (2004)',
               'Brasil (2008)',
               'Brasil (2016)',
               'A',
               None),
              ('Qual equipe foi campeã da NBA em 2016 após virada histórica?',
               'Golden State Warriors',
               'Cleveland Cavaliers',
               'San Antonio Spurs',
               'Miami Heat',
               'B',
               None),
              ('Em qual cidade foi fundada a FIFA (1904)?',
               'Zurique',
               'Paris',
               'Berlim',
               'Genebra',
               'B',
               None),
              ('Qual clube venceu a primeira Libertadores (1960)?',
               'Peñarol',
               'Independiente',
               'Santos',
               'Boca Juniors',
               'A',
               None),
              ('Que país tem mais títulos da Copa do Mundo?',
               'Alemanha',
               'Itália',
               'Brasil',
               'Argentina',
               'C',
               None),
              ("Quem é o 'Fenômeno' do futebol?",
               'Romário',
               'Ronaldo',
               'Ronaldinho',
               'Rivaldo',
               'B',
               None),
              ('Qual Grand Slam é disputado em piso de saibro?',
               'Wimbledon',
               'Roland Garros',
               'US Open',
               'Australian Open',
               'B',
               None),
              ("Quem é conhecido como 'O Rei' no basquete?",
               'LeBron James',
               'Kobe Bryant',
               'Michael Jordan',
               'Magic Johnson',
               'C',
               None),
              ('Qual seleção venceu a Copa do Mundo de 1998?',
               'Brasil',
               'França',
               'Alemanha',
               'Itália',
               'B',
               None),
              ('Em que país nasceu Ayrton Senna?',
               'Argentina',
               'Portugal',
               'Espanha',
               'Brasil',
               'D',
               None),
              ('Com que frequência as Olimpíadas ocorrem?', 
               '3 anos', 
               '5 anos', 
               '4 anos', 
               '6 anos', 
               'C', 
               None),
              ('Quem foi campeão da Copa América 2019?',
               'Argentina',
               'Chile',
               'Uruguai',
               'Brasil',
               'D',
               None),
              ("Quantos times existem na MLB?",
               '30',
               '20',
               '25',
               '24',
               'A',
               None),
              ('Qual país conquistou o 1º Mundial de Clubes da FIFA (2000)?',
               'Real Madrid',
               'Boca Juniors',
               'Manchester United',
               'Corinthians',
               'D',
               None),
              ('Qual esporte tem Grand Prix e escuderias?',
               'Motocross',
               'Rali',
               'NASCAR',
               'Fórmula 1',
               'D',
               None),
              ("Qual seleção é conhecida como 'La Roja'?",
               'Chile',
               'Portugal',
               'Espanha',
               'Suíça',
               'C',
               None),
              ('Qual torneio de tênis abre a temporada dos Grand Slams?',
               'Roland Garros',
               'Wimbledon',
               'US Open',
               'Australian Open',
               'D',
               None),
              ("Qual clube tem o apelido 'Rubro-Negro' no Brasil?",
               'Palmeiras',
               'Grêmio',
               'Flamengo',
               'Santos',
               'C',
               None),
                ("Qual seleção é apelidada de 'Laranja Mecânica'?", "Holanda", "Bélgica", "Suécia", "Dinamarca", "A", None),
                ("Quantos jogadores cada equipe tem em quadra no vôlei (sem líbero considerar posição extra)?", "5", "6", "7", "8", "B", None),
                ("Qual é a distância oficial da maratona?", "40 km", "41 km", "42,195 km", "43 km", "C", None),
                ("O clube alemão conhecido como 'Bávaros' é o:", "Borussia Dortmund", "Bayern de Munique", "Schalke 04", "Hamburgo", "B", None),
                ("No futebol, 'hat-trick' significa marcar:", "2 gols", "3 gols", "4 gols", "5 gols", "B", None),
                ("Qual torneio do golfe é disputado tradicionalmente em Augusta?", "US Open", "The Open", "PGA Championship", "Masters", "D", None),
                ("No basquete, o cronômetro de arremesso (shot clock) é de:", "20s", "24s", "30s", "35s", "B", None),
                ("Qual seleção é chamada de 'Três Leões'?", "Itália", "Inglaterra", "Escócia", "País de Gales", "B", None),
                ("Em qual país fica o circuito de Suzuka, clássico da F1?", "China", "Japão", "Coreia do Sul", "Singapura", "B", None),
                ("Em qual esporte a expressão 'birdie' é usada?", "Beisebol", "Golfe", "Críquete", "Rúgbi", "B", None),
                ("Qual país é potência no handebol masculino (várias vezes campeão mundial)?", "França", "Espanha", "Croácia", "Islândia", "A", None),
                ("No tênis, 40–40 é chamado de:", "Deuce", "Advantage", "Fault", "Tie", "A", None),
                ("Qual clube italiano é apelidado de 'Velha Senhora'?", "Milan", "Inter", "Juventus", "Lazio", "C", None),
                ("Em qual cidade acontece a famosa prova de ciclismo 'Paris–Roubaix' (chegada)?", "Roubaix", "Lille", "Amiens", "Calais", "A", None),
                ("Qual seleção venceu o primeiro Europeu (Euro 1960)?", "URSS", "Iugoslávia", "Espanha", "Alemanha Ocidental", "A", None),
                ("Em qual esporte existe a posição 'ponta-direita' tradicionalmente?", "Hóquei no gelo", "Handebol", "Críquete", "Polo aquático", "B", None),
                ("Qual destes clubes é da Turquia?", "Panathinaikos", "Fenerbahçe", "Steaua", "Partizan", "B", None),
                ("Qual país é referência histórica no sumô?", "China", "Coreia do Sul", "Japão", "Mongólia", "C", None)],
 'História': [('O que a imagem simboliza (evento de 1989 na Europa)?',
               'Primavera de Praga',
               'Tratado de Maastricht',
               'Queda do Muro de Berlim',
               'Reunificação Alemã',
               'C',
               'images/evento-1989.jpg'),
              ('Quem é o conquistador na imagem (fundou império até a Índia)?',
               'Júlio César',
               'Alexandre, o Grande',
               'Ciro, o Grande',
               'Aníbal',
               'B',
               'images/conquistador.jpg'),
              ('A estátua na imagem representa qual império clássico?',
               'Império Bizantino',
               'Império Romano',
               'Império Persa',
               'Império Otomano',
               'B',
               'images/estatua.jpg'),
              ('Em que ano terminou a Segunda Guerra Mundial?',
               '1944',
               '1945',
               '1946',
               '1947',
               'B',
               None),
              ("Quem foi esta figura histórica?", "Joana d'Arc", "Napoleão", "Catarina, a Grande", "Maria Antonieta", "D", "images/figura-historica.jpg"),
              ("Que construção é esta?", "Petra", "Muralha da China", "Partenon", "Coliseu", "C", "images/construcao-historica.jpg"),
              ('Quem proclamou a Independência do Brasil?',
               'Dom Pedro I',
               'José Bonifácio',
               'Marechal Deodoro',
               'Tiradentes',
               'A',
               None),
              ('Qual civilização construiu Machu Picchu?',
               'Maia',
               'Inca',
               'Asteca',
               'Olmeca',
               'B',
               None),
              ('Qual revolução marcou 1789 na França?',
               'Industrial',
               'Gloriosa',
               'Francesa',
               'Russa',
               'C',
               None),
              ('Quem foi derrotado em Waterloo (1815)?',
               'Napoleão Bonaparte',
               'Luís XIV',
               'Carlos Magno',
               'Robespierre',
               'A',
               None),
              ('Qual tratado encerrou a Primeira Guerra Mundial?',
               'Tordesilhas',
               'Versalhes',
               'Utrecht',
               'Paris (1763)',
               'B',
               None),
              ('Quem foi o primeiro presidente do Brasil?',
               'Marechal Deodoro da Fonseca',
               'Floriano Peixoto',
               'Campos Sales',
               'Prudente de Morais',
               'A',
               None),
              ('Qual império tinha Constantinopla como capital?',
               'Carolíngio',
               'Bizantino',
               'Romano do Ocidente',
               'Sacro Império Romano',
               'B',
               None),
              ('Quem liderou a Marcha do Sal (1930) na Índia?',
               'Nehru',
               'Gandhi',
               'Jinnah',
               'Tagore',
               'B',
               None),
              ('Qual império conquistou Tenochtitlán em 1521?',
               'Português',
               'Espanhol',
               'Inglês',
               'Holandês',
               'B',
               None),
              ('Qual pandemia assolou a Europa no século XIV?',
               'Gripe Espanhola',
               'Cólera',
               'Varíola',
               'Peste Negra',
               'D',
               None),
              ('Quem foi a monarca inglesa da era vitoriana?',
               'Elizabeth I',
               'Mary I',
               'Anne',
               'Victoria',
               'D',
               None),
              ('Qual cidade foi bombardeada por armas nucleares (uma delas) em 1945?',
               'Tóquio',
               'Osaka',
               'Kyoto',
               'Hiroshima',
               'D',
               None),
              ('Qual rota conectou por séculos Oriente e Ocidente?',
               'Rota do Âmbar',
               'Rota do Ouro',
               'Via Ápia',
               'Rota da Seda',
               'D',
               None),
              ('Qual navegação europeia chegou ao Brasil em 1500?',
               'Vasco da Gama',
               'Cristóvão Colombo',
               'Amerigo Vespucci',
               'Pedro Álvares Cabral',
               'D',
               None),
              ('Que império caiu em 476 d.C., marcando o fim da Antiguidade?',
               'Romano do Ocidente',
               'Bizantino',
               'Persa',
               'Otomano',
               'A',
               None),
              ('Quem foi o líder negro dos EUA que defendeu a não-violência?',
               'Malcolm X',
               'Frederick Douglass',
               'Rosa Parks',
               'Martin Luther King Jr.',
               'D',
               None),
              ('Qual foi a principal guerra do século XVII que devastou a Europa Central?',
               'Guerra dos Trinta Anos',
               'Guerra dos Sete Anos',
               'Guerra Civil Inglesa',
               'Guerra de Sucessão Espanhola',
               'A',
               None),
              ('Qual cidade-estado foi o berço da democracia direta?',
               'Esparta',
               'Roma',
               'Corinto',
               'Atenas',
               'D',
               None),
              ("Quem escreveu 'O Príncipe' (1532)?",
               'Maquiavel',
               'Erasmo',
               'Montesquieu',
               'Rousseau',
               'A',
               None),
              ('Qual foi a primeira civilização a desenvolver escrita cuneiforme?',
               'Egípcia',
               'Fenícia',
               'Suméria',
               'Persa',
               'C',
               None),
              ('Qual foi a exploração que contornou a África até a Índia (1497–1499)?',
               'Colombo',
               'Magalhães',
               'Vasco da Gama',
               'Cabral',
               'C',
               None),
              ('Qual reforma religiosa foi iniciada por Martinho Lutero?',
               'Contrarreforma',
               'Grande Cisma',
               'Reforma Protestante',
               'Anglicanismo',
               'C',
               None),
              ('Qual império dominou a Península Ibérica por séculos como Al-Andalus?',
               'Romano',
               'Visigodo',
               'Mouro',
               'Celta',
               'C',
               None),
              ('Qual navegação deu a volta ao mundo pela primeira vez?',
               'Magalhães-Elcano',
               'Colombo',
               'Vasco da Gama',
               'Cook',
               'A',
               None),
              ('Quem unificou a Alemanha em 1871 como chanceler?',
               'Kaiser Wilhelm II',
               'Frederico o Grande',
               'Bismarck',
               'Ludwig II',
               'C',
               None),
              ('Qual revolução derrubou o czarismo em 1917?',
               'Revolução Chinesa',
               'Revolução Cubana',
               'Revolução Russa',
               'Revolução Mexicana',
               'C',
               None),
               ("A cidade maia de Chichén Itzá fica no atual:", "México", "Guatemala", "Honduras", "Belize", "A", None),
               ("Quem foi conhecido como 'Libertador' em grande parte da América Andina?", "José de San Martín", "Simón Bolívar", "Bernardo O'Higgins", "José Artigas", "B", None),
               ("Independência dos EUA foi proclamada em:", "1776", "1789", "1812", "1861", "A", None),
               ("Qual civilização elaborou o Código de Hamurabi?", "Assíria", "Babilônica", "Hitita", "Persa", "B", None),
               ("Qual rainha egípcia teve relações políticas com Júlio César e Marco Antônio?", "Nefertiti", "Cleópatra", "Hatshepsut", "Meritaten", "B", None),
               ("Quem liderou a unificação da Itália no séc. XIX (figura chave militar)?", "Garibaldi", "Cavour", "Mazzini", "Vittorio Emanuele II", "A", None),
               ("O 'New Deal' foi implementado por qual presidente dos EUA?", "Truman", "FDR (Roosevelt)", "Eisenhower", "Hoover", "B", None),
               ("Qual batalha naval decisiva ocorreu em 1805?", "Trafalgar", "Jutlândia", "Lepanto", "Midway", "A", None),
               ("Que império tinha Tenochtitlán como capital antes da conquista?", "Asteca", "Inca", "Maya", "Olmeca", "A", None),
               ("Qual acordo pós-I Guerra redesenhou o Oriente Médio (mandatos)?", "Potsdam", "Sykes-Picot", "Yalta", "Camp David", "B", None),
               ("Quem foi o primeiro imperador de Roma?", "Júlio César", "Augusto", "Nero", "Trajano", "B", None),
               ("Qual revolução começou em 1910 e envolveu líderes como Zapata e Pancho Villa?", "Chinesa", "Mexicana", "Russa", "Iraniana", "B", None),
               ("A 'Guerra dos Cem Anos' foi principalmente entre:", "Inglaterra e França", "Espanha e Portugal", "Alemanha e Itália", "Suécia e Rússia", "A", None),
               ("Qual civilização construiu Petra?", "Nabateus", "Fenícios", "Assírios", "Hititas", "A", None),
               ("Qual tratado encerrou a Guerra Fria? (pergunta capciosa)", "Nenhum tratado único", "INF", "START I encerrou", "Tratado de Paris", "A", None),
               ("O 'Estado Novo' no Brasil foi liderado por:", "JK", "Getúlio Vargas", "Jânio Quadros", "Costa e Silva", "B", None),
               ("Qual conferência definiu a criação da ONU em 1945?", "Teerã", "São Francisco", "Yalta", "Postdam", "B", None),
               ("Qual navegação portuguesa explorou o litoral africano antes de 1500?", "Navegações de Diogo Cão", "Vikings", "Cook", "Cabot", "A", None),],
 'Jogos': [('Qual herói aparece na imagem?',
            'Zelda',
            'Ganondorf',
            'Link',
            'Pit',
            'C',
            'images/heroi.jpg'),
           ('Qual jogo é mostrado na capa (sandbox de 2013)?',
            'GTA IV',
            'GTA V',
            'Sleeping Dogs',
            'Mafia II',
            'B',
            'images/jogo-2013.jpg'),
           ('Qual jogo de blocos em mundo aberto aparece na imagem?',
            'Roblox',
            'Terraria',
            "No Man's Sky",
            'Minecraft',
            'D',
            'images/jogo-blocos.jpg'),
           ("Que jogo é este?", "Among Us", "Fall Guys", "Gang Beasts", "Human: Fall Flat", "A", "images/jogo-x.jpg"),
           ("Estes símbolos pertencem a qual controle?", "Xbox", "PlayStation", "Nintendo", "Atari", "B", "images/simbolos-controle.jpg"),
           ('Qual é o nome do irmão do Mario?', 'Wario', 'Luigi', 'Yoshi', 'Toad', 'B', None),
           ('Em que ano foi lançado o primeiro PlayStation?',
            '1993',
            '1994',
            '1995',
            '1996',
            'B',
            None),
           ('Quem criou o conceito original de Tetris?',
            'Hideo Kojima',
            'Shigeru Miyamoto',
            'Alexey Pajitnov',
            'Sid Meier',
            'C',
            None),
           ('Em qual franquia surgiu Master Chief?',
            'Gears of War',
            'Destiny',
            'Halo',
            'Doom',
            'C',
            None),
           ("Qual jogo de luta popularizou 'Finish Him!'?",
            'Tekken',
            'Mortal Kombat',
            'Killer Instinct',
            'Street Fighter',
            'B',
            None),
           ("Qual console recebeu 'Ocarina of Time' originalmente?",
            'GameCube',
            'SNES',
            'Nintendo 64',
            'Wii',
            'C',
            None),
           ("Qual estúdio criou 'The Witcher 3'?",
            'CD Projekt Red',
            'Bethesda',
            'BioWare',
            'Obsidian',
            'A',
            None),
           ('Qual jogo popularizou o battle royale em 2017?',
            'Fortnite',
            'H1Z1',
            'PUBG',
            'Apex Legends',
            'C',
            None),
           ("Qual desenvolvedora criou 'Dark Souls'?",
            'FromSoftware',
            'Capcom',
            'Konami',
            'Square Enix',
            'A',
            None),
           ('Em qual jogo a cidade de Raccoon City é cenário?',
            'Dead Space',
            'Resident Evil',
            'Silent Hill',
            'The Last of Us',
            'B',
            None),
           ('Qual personagem coleta anéis em super velocidade?',
            'Crash',
            'Sonic',
            'Spyro',
            'Rayman',
            'B',
            None),
           ("Quem produz a série 'Gran Turismo'?",
            'Turn 10',
            'Polyphony Digital',
            'Codemasters',
            'EA Canada',
            'B',
            None),
           ('Qual indie de 2015 explora o fundo do mar e o luto?',
            'Abzû',
            'Journey',
            'Firewatch',
            'Inside',
            'A',
            None),
           ('Qual heroína usa o traje Power Suit?',
            'Bayonetta',
            'Samus Aran',
            'Jill Valentine',
            'Aloy',
            'B',
            None),
           ("Qual jogo popularizou o inimigo 'creeper'?",
            "Don't Starve",
            'Terraria',
            'Minecraft',
            'Subnautica',
            'C',
            None),
           ('Em qual série aparece a cidade submersa Rapture (DLC/coleções)?',
            'Dishonored',
            'Prey',
            'Deus Ex',
            'Bioshock',
            'D',
            None),
           ('Qual franquia da Nintendo apresenta Hyrule?',
            'Metroid',
            'Kirby',
            'Zelda',
            'Star Fox',
            'C',
            None),
           ('Quem é o encanador rival amarelo do Mario?',
            'Wario',
            'Waluigi',
            'Toad',
            'Bowser',
            'A',
            None),
           ("Qual jogo tem o modo 'Creative' amplamente usado para construir?",
            'Minecraft',
            'Roblox',
            'The Sims',
            'Cities: Skylines',
            'A',
            None),
           ('Qual empresa lançou o console Dreamcast?',
            'Sega',
            'Nintendo',
            'Sony',
            'Atari',
            'A',
            None),
           ("Qual é o subtítulo do jogo 'Zelda: BOTW'?",
            'Breath of the Wild',
            'Breath of the Water',
            'Born of the Wild',
            'Breath of the Witch',
            'A',
            None),
           ('Qual jogo da Rockstar se passa no Velho Oeste?',
            'Max Payne',
            'Bully',
            'L.A. Noire',
            'Red Dead Redemption',
            'D',
            None),
           ("Qual plataforma recebeu 'Half-Life 2' no lançamento?",
            'PS2',
            'PS3',
            'Xbox One',
            'PC',
            'D',
            None),
           ('Qual jogo tem as classes Scout, Heavy e Medic?',
            'Overwatch',
            'Valorant',
            'Paladins',
            'Team Fortress 2',
            'D',
            None),
           ('Qual série tem o personagem Geralt de Rívia?',
            'The Elder Scrolls',
            'Dragon Age',
            'Fable',
            'The Witcher',
            'D',
            None),
           ("Qual é o antagonista principal de 'The Legend of Zelda' clássico?",
            'Ridley',
            'Bowser',
            'Ganondorf',
            'Giygas',
            'C',
            None),
           ("Qual jogo de 2016 popularizou o termo 'Battle Royale' gratuito?",
            'PUBG',
            'Apex Legends',
            'Warzone',
            'Fortnite',
            'D',
            None),
            ("Qual empresa criou 'The Sims'?", "Maxis", "EA Canada", "Ubisoft", "Blizzard", "A", None),
            ("Em 'Portal', qual objeto é o companheiro do jogador?", "Weighted Companion Cube", "Pikmin", "Navi", "Claptrap", "A", None),
            ("Em qual franquia aparece a bebida 'Nuka-Cola'?", "Metro", "Fallout", "Borderlands", "Bioshock", "B", None),
            ("Qual série popularizou o termo 'Souls-like'?", "Devil May Cry", "Dark Souls", "God of War", "Ninja Gaiden", "B", None),
            ("Qual jogo indie de 2016 sobre comunicação por rádio no parque nacional?", "Firewatch", "Inside", "Oxenfree", "The Witness", "A", None),
            ("Qual personagem é caçadora de máquinas em um mundo pós-colapso?", "Aloy", "Ellie", "Ciri", "Jill", "A", None),
            ("Qual produtor da Nintendo é conhecido como 'pai do Mario'?", "Satoru Iwata", "Shigeru Miyamoto", "Reggie Fils-Aimé", "Eiji Aonuma", "B", None),
            ("Qual série tem 'Vaults' subterrâneas numeradas?", "Stalker", "Fallout", "Wasteland", "Metro", "B", None),
            ("Qual jogo apresenta carros acrobáticos em arenas com bola gigante?", "Destruction Derby", "Rocket League", "Trackmania", "Wipeout", "B", None),
            ("Qual jogo de 2D-metroidvania com insetos ganhou destaque em 2017?", "Ori", "Hollow Knight", "Dead Cells", "Salt and Sanctuary", "B", None),
            ("Qual empresa desenvolveu 'Overwatch'?", "Riot Games", "Blizzard", "Valve", "Gearbox", "B", None),
            ("Qual série tem a cidade de 'Yharnam'?", "Dark Souls", "Bloodborne", "Elden Ring", "Nioh", "B", None),
            ("Em qual franquia aparece o item 'Poké Ball'?", "Digimon", "Yo-kai Watch", "Pokémon", "Monster Hunter", "C", None),
            ("Qual jogo tem a frase 'War. War never changes.'?", "Company of Heroes", "Call of Duty", "Fallout", "Gears of War", "C", None),
            ("Qual jogo de estratégia em tempo real popularizou zerg/protoss/terran?", "Warcraft", "StarCraft", "Age of Empires", "C&C", "B", None),
            ("Qual série apresenta a vila de 'Pelican Town'?", "Animal Crossing", "Rune Factory", "Stardew Valley", "Harvest Moon (Friends of Mineral Town)", "C", None),
            ("Qual estúdio fez 'Hades'?", "Supergiant Games", "Klei", "Motion Twin", "Housemarque", "A", None),
            ("Qual é o nome do bloco em forma de T no Tetris clássico?", "T-Tetromino", "Tri-Block", "T-Piece", "Tet-Three", "A", None),],
 'Lógica': [('A figura mostra um sólido com 6 faces quadradas. Qual é?',
             'Cilindro',
             'Prisma triangular',
             'Cubo',
             'Esfera',
             'C',
             'images/solido.jpg'),
            ('A figura que representa toda a região plana é?',
             'Circunferência',
             'Elipse',
             'Círculo',
             'Hipérbole',
             'C',
             'images/curva-fechada.jpg'),
            ('Que polígono está na imagem?',
             'Hexágono',
             'Pentágono',
             'Heptágono',
             'Quadrilátero',
             'B',
             'images/poligono.jpg'),
            ("Qual peça completa o padrão na imagem?", "▲", "■", "●", "◆", "C", "images/formas.jpg"),
            ("Qual rota chega mais rápido se todas as ruas têm o mesmo tempo: A→B→D ou A→C→D?", "A→B→D", "A→C→D", "As duas são iguais", "Não é possível saber", "C", "images/rotas.jpg"),
            ('Complete: 3, 6, 12, 24, …', '36', '42', '48', '54', 'C', None),
            ('Se 5 máquinas fazem 5 peças em 5 minutos, 100 máquinas fazem 100 peças em…',
             '1 hora e 30 minutos',
             '50 minutos',
             '100 minutos',
             '1000 segundos',
             'A',
             None),
            ('Todos os mamíferos respiram. Baleias respiram. Logo…',
             'Baleias não são mamíferos',
             'Baleias são mamíferos',
             'Baleias não respiram',
             'Nenhuma das anteriores',
             'B',
             None),
            ('Qual número falta? 1, 1, 2, 3, 5, 8, …', '10', '11', '12', '13', 'D', None),
            ('Se todo A é B e todo B é C, então…',
             'Todo A é C',
             'Nenhum A é C',
             'Alguns A não são C',
             'Não é possível concluir',
             'A',
             None),
            ('Qual próxima figura lógica: ▲, ■, ◆, ■, …', '■', '▲', '○', '◆', 'B', None),
            ("Em um grupo, todos são honestos ou mentirosos. Se alguém diz 'sou mentiroso', então…",
             'É honesto',
             'É mentiroso',
             'É contraditório',
             'Impossível determinar',
             'C',
             None),
            ('Se hoje é terça e faltam 10 dias para o evento, ele será…',
             'Domingo',
             'Sábado',
             'Sexta',
             'Segunda',
             'C',
             None),
            ('Menor número positivo divisível por 3, 4 e 5?', '30', '60', '120', '15', 'A', None),
            ('Um trem percorre 300 km em 3h. Velocidade média?',
             '80 km/h',
             '90 km/h',
             '100 km/h',
             '110 km/h',
             'C',
             None),
            ("Negação de 'A ou B' é verdadeira. Então…",
             'A e B verdadeiros',
             'A e B falsos',
             'Pelo menos A verdadeiro',
             'Exatamente um verdadeiro',
             'B',
             None),
            ('Próximo primo: 2, 3, 5, 7, 11, …', '12', '13', '14', '15', 'B', None),
            ('Soma interna 540° pertence a…',
             'Pentágono',
             'Hexágono',
             'Heptágono',
             'Octógono',
             'A',
             None),
            ('Se 20% de x é 50, x é…', '200', '220', '240', '250', 'D', None),
            ('Área de um retângulo 5x9?', '35', '40', '45', '54', 'C', None),
            ('Se P ⇒ Q é falso, então…',
             'P verdadeiro e Q falso',
             'P falso e Q verdadeiro',
             'Ambos verdadeiros',
             'Ambos falsos',
             'A',
             None),
            ('Se três números somam 60 e dois são 15 e 23, o terceiro é…',
             '20',
             '21',
             '22',
             '19',
             'C',
             None),
            ('Se 8 é 2³, então 32 é…', '2⁴', '2⁵', '2⁶', '2⁷', 'B', None),
            ('Se x + x/2 = 18, então x é…', '10', '11', '12', '14', 'C', None),
            ('Qual é a mediana de 2, 3, 9, 11, 15?', '9', '11', '3', '7', 'A', None),
            ('Qual é a moda de 1, 2, 2, 3, 4?', '1', '2', '3', '4', 'B', None),
            ('Se hoje é o 3º dia do mês então daqui 30 dias será o…',
             '2º',
             '4º',
             '5º',
             '3º de novo',
             'D',
             None),
            ('Se um ângulo agudo é menor que 90°, 47° é…',
             'Reto',
             'Obtuso',
             'Raso',
             'Agudo',
             'D',
             None),
            ('Se o dobro de y é 18, então y é…', '7', '8', '10', '9', 'D', None),
            ('Na sequência 1,4,9,16,… o próximo é…', '20', '24', '26', '25', 'D', None),
            ('Qual fração é equivalente a 0,5?', '1/3', '1/2', '2/3', '3/4', 'B', None),
            ('Se 3x = 27, então x é…', '6', '7', '8', '9', 'D', None),
            ("Se todo cachorro é leal e Max é cachorro, podemos concluir que:", "Max é leal", "Max não é leal", "Nada se conclui", "Max é gato", "A", None),
            ("Numa fila, Ana está à frente de Bia e atrás de Caio. Quem está no meio?", "Ana", "Bia", "Caio", "Nenhum", "A", None),
            ("Se apenas membros do clube usam broche azul, e Júlio usa broche azul, então:", "Júlio não é do clube", "Júlio é do clube", "Júlio é do time", "Não se sabe", "B", None),
            ("Todos os livros da prateleira A são de ficção. Alguns livros da estante são da prateleira A. Logo:", "Alguns livros da estante são de ficção", "Todos da estante são de ficção", "Nenhum da estante é de ficção", "Não se pode concluir", "A", None),
            ("Três amigos — Léo, Mia e Nia — gostam de chá, café e suco (um cada). Léo não gosta de café; Mia não gosta de suco. Quem gosta de café?", "Léo", "Mia", "Nia", "Nenhum", "C", None),
            ("Se uma afirmação é verdadeira apenas quando chove, e não está chovendo, então a afirmação é:", "Verdadeira", "Falsa", "Verdadeira e falsa", "Indeterminada", "B", None),
            ("Qual item não pertence ao grupo?", "Ônibus", "Trem", "Metrô", "Bicicleta", "D", None),
            ("Se Pedro mente às segundas e diz 'hoje é segunda', então hoje é:", "Segunda", "Terça", "Domingo", "Quarta", "B", None),
            ("Numa gaveta há 3 pares de meias de cores diferentes. No escuro, quantas meias no mínimo precisa pegar para garantir um par?", "2", "3", "4", "5", "C", None),
            ("Qual sequência lógica completa: Norte, Leste, Sul, ...", "Oeste", "Norte", "Sul", "Leste", "A", None),
            ("Uma chave abre portas redondas e quadradas. Porta A é redonda; B é triangular; C é quadrada. Quais portas podem ser abertas?", "A e C", "A e B", "B e C", "A apenas", "A", None),
            ("Se nenhum carro vermelho é elétrico e alguns elétricos são caros, então:", "Alguns carros vermelhos são caros", "Nenhum carro vermelho é caro", "Nada se conclui sobre carros vermelhos serem caros", "Todos os carros são caros", "C", None),
            ("A palavra que completa a série: CASA, CASO, ...", "CASSO", "CASA", "CASU", "CASAÓ", "C", None),
            ("Se o próximo dia após amanhã é quinta, então hoje é:", "Segunda", "Terça", "Quarta", "Sexta", "A", None),
            ("Se 'alguns artistas são músicos' é verdadeiro, então qual é necessariamente falso?", "Todos artistas são músicos", "Nenhum artista é músico", "Alguns músicos são artistas", "Nada é necessariamente falso", "B", None),
            ("Na ordem alfabética, qual vem logo após 'PATO'?", "PATOA", "PATOR", "PATU", "PATOS", "D", None),
            ("Se toda tarde há treino e hoje não houve treino, então:", "Não é tarde", "É tarde", "É manhã", "É noite", "A", None),
            ("Qual opção completa: 2ª, 4ª, 6ª, ...", "7ª", "8ª", "5ª", "3ª", "B", None)],
 'Música': [('Qual banda aparece na imagem?',
             'The Beatles',
             'Queen',
             'Pink Floyd',
             'The Who',
             'B',
             'images/quarteto-britanico.jpg'),
            ('Quem é o artista na imagem?',
             'Chris Cornell',
             'Stevie Wonder',
             'Chester Bennington',
             'Kurt Cobain',
             'C',
             'images/artista.jpg'),
            ("Quem é a cantora na imagem?",
             'Lady Gaga',
             'Adele',
             'Beyoncé',
             'Rihanna',
             'B',
             'images/cantora.jpg'),
            ("Quem é este artista?", "Adam Levine", "Joshua Scott ", "Nick Carter", "Justin Timberlake", "D", "images/cantor.jpeg"),
            ("Que capa de álbum é esta?", "The Velvet Underground & Nico", "Nevermind", "Unknown Pleasures", "The Queen Is Dead", "A", "static/images/capa-album.jpg"),
            ('Quem foi o baterista dos Beatles?',
             'Ringo Starr',
             'John Bonham',
             'Phil Collins',
             'Charlie Watts',
             'A',
             None),
            ("Qual banda lançou 'The Dark Side of the Moon'?",
             'Pink Floyd',
             'Led Zeppelin',
             'The Doors',
             'Queen',
             'A',
             None),
            ("Quem é conhecido como o 'Rei do Rock'?",
             'Elvis Presley',
             'Chuck Berry',
             'Jerry Lee Lewis',
             'Buddy Holly',
             'A',
             None),
            ("Qual rapper lançou 'To Pimp a Butterfly'?",
             'Kendrick Lamar',
             'Kanye West',
             'J. Cole',
             'Drake',
             'A',
             None),
            ("Qual cantora lançou o álbum 'Lemonade'?",
             'Rihanna',
             'Beyoncé',
             'Adele',
             'Alicia Keys',
             'B',
             None),
            ("Qual banda grunge popularizou 'Nevermind'?",
             'Pearl Jam',
             'Nirvana',
             'Soundgarden',
             'Alice in Chains',
             'B',
             None),
            ('Qual compositor ficou completamente surdo no fim da vida?',
             'Mozart',
             'Beethoven',
             'Bach',
             'Tchaikovsky',
             'B',
             None),
            ('Quem é o baixista/vocalista do Rush?',
             'Alex Lifeson',
             'Geddy Lee',
             'Neil Peart',
             'John Entwistle',
             'B',
             None),
            ('Qual movimento surgiu no Bronx nos anos 70?',
             'Disco',
             'Hip hop',
             'Punk',
             'New Wave',
             'B',
             None),
            ("Quem é a 'Rainha do Fado'?",
             'Mariza',
             'Dulce Pontes',
             'Carminho',
             'Amália Rodrigues',
             'D',
             None),
            ("Qual banda lançou 'Californication'?",
             'Green Day',
             'The Strokes',
             'Foo Fighters',
             'Red Hot Chili Peppers',
             'D',
             None),
            ("Quem cantou 'Bad Guy'?", 'Billie Eilish', 'Dua Lipa', 'Lorde', 'Halsey', 'A', None),
            ('Qual guitarrista incendiou a guitarra em Monterey (1967)?',
             'Eric Clapton',
             'Pete Townshend',
             'Jimmy Page',
             'Jimi Hendrix',
             'D',
             None),
            ('Qual gênero é associado ao acordeon no Nordeste brasileiro?',
             'Bossa Nova',
             'Frevo',
             'Samba',
             'Forró',
             'D',
             None),
            ('Qual produtor é creditado por popularizar o G-funk?',
             'Dr. Dre',
             'Snoop Dogg',
             'Ice Cube',
             'Pharrell Williams',
             'A',
             None),
            ("Qual é a voz de 'Rolling in the Deep'?",
             'Beyoncé',
             'Amy Winehouse',
             'Alicia Keys',
             'Adele',
             'D',
             None),
            ("Qual banda é do álbum 'OK Computer'?",
             'Radiohead',
             'U2',
             'Coldplay',
             'Oasis',
             'A',
             None),
            ("Qual cantor brasileiro lançou 'Nada Como um Dia…'?",
             'Raimundos',
             'Charlie Brown Jr.',
             'Titãs',
             "Racionais MC's",
             'D',
             None),
            ('Qual é o instrumento principal de John Coltrane?',
             'Trompete',
             'Piano',
             'Saxofone',
             'Contrabaixo',
             'C',
             None),
            ("Qual cantora pop lançou 'Future Nostalgia'?",
             'Katy Perry',
             'Ariana Grande',
             'Dua Lipa',
             'Selena Gomez',
             'C',
             None),
            ('Quem é o guitarrista do Queen?',
             'Jimmy Page',
             'Angus Young',
             'Brian May',
             'Slash',
             'C',
             None),
            ("Qual banda tem o hit 'Bohemian Rhapsody'?",
             'The Beatles',
             'ABBA',
             'Queen',
             'Bee Gees',
             'C',
             None),
            ('Qual é o verdadeiro nome de Lady Gaga?',
             'Robyn Fenty',
             'Alecia Moore',
             'Stefani Germanotta',
             'Katheryn Hudson',
             'C',
             None),
            ("Qual dupla brasileira lançou 'Domingo de Manhã'?",
             'Jorge & Mateus',
             'Zé Neto & Cristiano',
             'Marcos & Belutti',
             'Henrique & Juliano',
             'C',
             None),
            ("Qual artista é famoso por 'Purple Rain'?",
             'Michael Jackson',
             'George Michael',
             'Prince',
             'Lionel Richie',
             'C',
             None),
            ("Qual banda britânica tem o álbum 'A Night at the Opera'?",
             'The Beatles',
             'The Who',
             'Queen',
             'Pink Floyd',
             'C',
             None),
            ("Qual banda britânica lançou o álbum 'The Bends'?",
             'Oasis',
             'Blur',
             'Coldplay',
             'Radiohead',
             'D',
             None),
            ("Qual alter-ego famoso de David Bowie nos anos 70?", "Aladdin Sane", "Ziggy Stardust", "Thin White Duke", "Major Tom", "B", None),
            ("Qual álbum do Metallica tem a faixa-título 'Master of Puppets'?", "Ride the Lightning", "Master of Puppets", "…And Justice for All", "Kill 'Em All", "B", None),
            ("Qual banda britânica emplacou 'Wonderwall' em 1995?", "Blur", "Radiohead", "Oasis", "The Verve", "C", None),
            ("Em qual cidade nasceu Mozart?", "Viena", "Salzburgo", "Praga", "Munique", "B", None),
            ("Qual movimento brasileiro é associado a Gilberto Gil e Caetano Veloso?", "Manguebeat", "Bossa Nova", "Tropicália", "Jovem Guarda", "C", None),
            ("'Stairway to Heaven' é de qual banda?", "Led Zeppelin", "Deep Purple", "Yes", "Queen", "A", None),
            ("A cantora Elis Regina é frequentemente associada a qual estilo?", "Sertanejo", "Bossa/MPB", "Samba-enredo", "Forró", "B", None),
            ("Qual rapper lançou 'Illmatic' (1994)?", "Nas", "Jay-Z", "The Notorious B.I.G.", "Rakim", "A", None),
            ("Qual banda tem o vocalista Bono?", "U2", "The Smiths", "The Cure", "R.E.M.", "A", None),
            ("'Fast Car' é canção de:", "Tracy Chapman", "Sheryl Crow", "Alanis Morissette", "Jewel", "A", None),
            ("Qual produtor é associado ao 'Wall of Sound'?", "Phil Spector", "Rick Rubin", "Quincy Jones", "Brian Eno", "A", None),
            ("'Clocks' tornou-se um hit de qual banda?", "Coldplay", "Keane", "Travis", "Snow Patrol", "A", None),
            ("'Nothing Else Matters' é de:", "Pearl Jam", "Metallica", "Guns N' Roses", "Scorpions", "B", None),
            ("Qual cantora brasileira é conhecida como 'Pimentinha'?", "Gal Costa", "Beth Carvalho", "Elis Regina", "Rita Lee", "C", None),
            ("'Back to Black' é um álbum de:", "Adele", "Amy Winehouse", "Florence Welch", "Lana Del Rey", "B", None),
            ("Qual DJ/produtor é conhecido pelo álbum 'Discovery' (2001)?", "Daft Punk", "Fatboy Slim", "Moby", "The Chemical Brothers", "A", None),
            ("'Alive' (1991) é de qual banda grunge?", "Soundgarden", "Pearl Jam", "Nirvana", "Alice in Chains", "B", None),
            ("'Zebra' e 'Te Devoro' são sucessos de:", "Djavan", "Milton Nascimento", "Gilberto Gil", "Lenine", "A", None)],
 'TV/Cinema': [('Quem é a atriz na imagem?',
                'Sophie Turner',
                'Emilia Clarke',
                'Natalie Dormer',
                'Lena Headey',
                'B',
                'images/atriz.jpg'),
               ('Qual filme é mostrado no pôster?',
                'Minority Report',
                'Blade Runner',
                'Matrix',
                'Tron',
                'C',
                'images/poster.jpg'),
               ('Quem aparece caracterizado como pirata na imagem?',
                'Johnny Depp',
                'Orlando Bloom',
                'Geoffrey Rush',
                'Tom Hardy',
                'A',
                '/images/pirata.jpeg'),
               ("De qual ícone é esta silhueta?", "Hitchcock", "Kubrick", "Welles", "Coppola", "A", "images/silhueta.jpg"),
               ("Esta estatueta representa qual premiação?", "BAFTA", "Globo de Ouro", "Oscar", "César", "C", "images/estatueta.jpg"),
               ("Em qual cidade se passa a maior parte de 'Friends'?",
                'Nova York',
                'Los Angeles',
                'Chicago',
                'Boston',
                'A',
                None),
               ("Quem dirigiu 'Jurassic Park' (1993)?",
                'Steven Spielberg',
                'James Cameron',
                'Ridley Scott',
                'George Lucas',
                'A',
                None),
               ('Quem interpretou Wolverine na maior parte da franquia X-Men?',
                'Hugh Jackman',
                'Christian Bale',
                'Robert Downey Jr.',
                'Chris Hemsworth',
                'A',
                None),
               ("Qual vilão clássico revela ser pai em 'O Império Contra-Ataca'?",
                'Darth Vader',
                'Kylo Ren',
                'Darth Maul',
                'General Grievous',
                'A',
                None),
               ('Qual filme ganhou o Oscar de Melhor Filme em 2020?',
                '1917',
                'Coringa',
                'Parasita',
                'Era uma Vez em… Hollywood',
                'C',
                None),
               ('Qual série se passa na fictícia Hawkins, nos anos 80?',
                'Stranger Things',
                'Dark',
                'The OA',
                'Black Mirror',
                'A',
                None),
               ("Quem dirigiu 'A Origem' (Inception)?",
                'Christopher Nolan',
                'Sam Mendes',
                'Guy Ritchie',
                'David Fincher',
                'A',
                None),
               ('Qual trilogia apresenta Mordor e o Um Anel?',
                'Harry Potter',
                'O Senhor dos Anéis',
                'Nárnia',
                'Percy Jackson',
                'B',
                None),
               ("Qual é o nome do universo compartilhado da Marvel no cinema?", "DCU", "MCU", "DCEU", "FoxVerse", "B", None),
               ('Qual animação da Pixar personifica emoções?',
                'Soul',
                'Viva',
                'Up',
                'Divertida Mente',
                'D',
                None),
               ('Quem dublou Buzz Lightyear (versão original)?',
                'Tom Hanks',
                'Tim Allen',
                'Robin Williams',
                'Jim Carrey',
                'B',
                None),
               ("Qual diretor assinou 'La La Land'?",
                'Baz Luhrmann',
                'Greta Gerwig',
                'Richard Linklater',
                'Damien Chazelle',
                'D',
                None),
               ('Qual filme de 2015 trouxe de volta Max e Furiosa?',
                'Sicario',
                'The Revenant',
                'Mad Max: Estrada da Fúria',
                'Ex Machina',
                'C',
                None),
               ('Qual série medieval da HBO tem a Casa Stark?',
                'Vikings',
                'Game of Thrones',
                'The Witcher',
                'The Last Kingdom',
                'B',
                None),
               ("Em qual filme ouvimos 'Run, Forrest, run!'?",
                'The Shawshank Redemption',
                'Pulp Fiction',
                'Se7en',
                'Forrest Gump',
                'D',
                None),
               ("Quem interpreta Eleven em 'Stranger Things'?",
                'Natalia Dyer',
                'Sadie Sink',
                'Winona Ryder',
                'Millie Bobby Brown',
                'D',
                None),
               ('Qual animador/estúdio criou Mickey Mouse?',
                'Hanna-Barbera',
                'DreamWorks',
                'Illumination',
                'Walt Disney',
                'D',
                None),
               ("Qual filme de 1999 popularizou o 'bullet time'?",
                'Clube da Luta',
                'Beleza Americana',
                'O Sexto Sentido',
                'Matrix',
                'D',
                None),
               ("Quem dirigiu 'Blade Runner 2049'?",
                'Ridley Scott',
                'Neill Blomkamp',
                'Denis Villeneuve',
                'Alex Garland',
                'C',
                None),
               ('Qual série policial acompanha um professor de química e seu ex-aluno?',
                'Better Call Saul',
                'Breaking Bad',
                'Narcos',
                'Ozark',
                'B',
                None),
               ('Qual filme ganhou Melhor Filme em 2019 (Academy Awards)?',
                'Roma',
                'Bohemian Rhapsody',
                'Green Book',
                'A Favorita',
                'C',
                None),
               ('Qual é o nome do brinquedo cowboy em Toy Story?',
                'Buzz',
                'Woody',
                'Jessie',
                'Rex',
                'B',
                None),
               ("Qual diretor é conhecido por tramas complexas como 'Tenet'?",
                'Quentin Tarantino',
                'David Fincher',
                'Christopher Nolan',
                'Paul Thomas Anderson',
                'C',
                None),
               ('Em qual série o advogado Saul Goodman aparece inicialmente?',
                'Better Call Saul',
                'Breaking Bad',
                'Fargo',
                'Narcos',
                'B',
                None),
               ('Qual filme musical de 2016 tem números de dança em LA?',
                'The Greatest Showman',
                'A Star Is Born',
                'La La Land',
                'Into the Woods',
                'C',
                None),
               ('Qual saga espacial apresenta a família Skywalker?',
                'Star Trek',
                'Star Wars',
                'Duna',
                'Guardians of the Galaxy',
                'B',
                None),
               ("Qual cineasta dirigiu 'A Chegada' (Arrival)?",
                'Christopher Nolan',
                'James Cameron',
                'Denis Villeneuve',
                'Ron Howard',
                'C',
                None),
                ("Qual série se passa em Scranton e acompanha o cotidiano de um escritório?", "Parks and Recreation", "The Office (US)", "Brooklyn Nine-Nine", "30 Rock", "B", None),
                ("Qual estúdio é cofundado por Hayao Miyazaki?", "Laika", "Aardman", "Studio Ghibli", "Illumination", "C", None),
                ("Quem dirigiu 'Os Bons Companheiros' (Goodfellas)?", "Martin Scorsese", "Francis Ford Coppola", "Brian De Palma", "Michael Mann", "A", None),
                ("Em 'O Iluminado', o hotel se chama:", "Overlook", "Bates", "Continental", "Ambassador", "A", None),
                ("Qual série policial se passa em Baltimore e é elogiada pelo realismo?", "True Detective", "The Wire", "Mindhunter", "The Shield", "B", None),
                ("Quem interpretou a Imperatriz Furiosa no prelúdio 'Furiosa' (2024)?", "Charlize Theron", "Anya Taylor-Joy", "Emily Blunt", "Mackenzie Davis", "B", None),
                ("Qual animação tem uma casa suspensa por balões e um explorador idoso?", "Viva", "Up", "Luca", "Encanto", "B", None),
                ("Qual diretor é famoso pelo suspense e por aparecer em cameos de seus filmes?", "Alfred Hitchcock", "Billy Wilder", "Fritz Lang", "John Huston", "A", None),
                ("Qual série mistura fantasia e política no continente de Westeros, mas é um spin-off/prelúdio?", "The Witcher: Blood Origin", "House of the Dragon", "The Rings of Power", "Willow", "B", None),
                ("Quem dirigiu 'No Country for Old Men'?", "Os Coen", "Paul Thomas Anderson", "Clint Eastwood", "David Fincher", "A", None),
                ("Qual filme de 1995 tem o assassino que usa pecados capitais?", "Se7en", "Heat", "The Usual Suspects", "L.A. Confidential", "A", None),
                ("Qual série acompanha um caçador de recompensas e uma criança sensível à Força?", "Andor", "The Book of Boba Fett", "The Mandalorian", "Obi-Wan Kenobi", "C", None),
                ("Quem dirigiu 'O Labirinto do Fauno'?", "Cuarón", "Guillermo del Toro", "Iñárritu", "Álex de la Iglesia", "B", None),
                ("Qual heroína luta contra alienígenas na nave Nostromo?", "Ellen Ripley", "Sarah Connor", "Trinity", "Leeloo", "A", None),
                ("Qual série acompanha mafiosos de Nova Jersey e seu terapeuta?", "The Sopranos", "Boardwalk Empire", "Ray Donovan", "Narcos", "A", None),
                ("'Cidade de Deus' é dirigido por:", "Kleber Mendonça Filho", "Fernando Meirelles", "José Padilha", "Walter Salles", "B", None),
                ("Qual diretor assinou 'Whiplash'?", "Damien Chazelle", "Tom Hooper", "Sam Mendes", "David O. Russell", "A", None),
                ("Qual filme tem o 'espião anônimo' conhecido apenas como 'O Motorista'?", "Drive", "Baby Driver", "Collateral", "The Transporter", "A", None)]}


def main():
    Base.metadata.create_all(engine)
    db = SessionLocal()
    try:
        count = db.query(Question).count()
        if count == 0:
            for theme, rows in SEED.items():
                for (st, a, b, c, d, corr, images) in rows:
                    db.add(Question(
                        theme=theme,
                        statement=st,
                        opt_a=a, opt_b=b, opt_c=c, opt_d=d,
                        correct=corr,
                        image_url=images
                    ))
            db.commit()
            print("Banco populado com perguntas!")
        else:
            print(f"Já existem {count} perguntas; nada a fazer.")
    finally:
        db.close()

if __name__ == "__main__":
    main()