import random
from models import Base, engine, SessionLocal, Question

SEED = {'Diversos': [('O que está na imagem (monumento do Egito)?',
               'Muralha da China',
               'Pirâmides de Gizé',
               'Torre Eiffel',
               'Coliseu',
               'B',
               '/static/img/piramides.jpg'),
              ('Qual invenção está na imagem (popularizada por Edison)?',
               'Telégrafo',
               'Lâmpada elétrica',
               'Fotografia',
               'Rádio',
               'B',
               '/static/img/lamp.jpg'),
              ('Qual bandeira (cruz azul sobre fundo amarelo) aparece?',
               'Noruega',
               'Suécia',
               'Islândia',
               'Finlândia',
               'B',
               '/static/img/sweden.jpg'),
              ('Qual é o maior planeta do Sistema Solar?',
               'Saturno',
               'Júpiter',
               'Urano',
               'Netuno',
               'B',
               None),
              ('Qual animal dorme de cabeça para baixo?',
               'Morcego',
               'Bicho-preguiça',
               'Coruja',
               'Gato',
               'A',
               None),
              ('Qual é a capital da Islândia?',
               'Oslo',
               'Reykjavik',
               'Estocolmo',
               'Helsinque',
               'B',
               None),
              ('Qual é o metal líquido à temperatura ambiente?',
               'Mercúrio',
               'Gálio',
               'Sódio',
               'Césio',
               'A',
               None),
              ("Qual país é conhecido como 'Terra do Sol Nascente'?",
               'China',
               'Japão',
               'Coreia do Sul',
               'Vietnã',
               'B',
               None),
              ('Qual oceano é o maior em área?',
               'Atlântico',
               'Pacífico',
               'Índico',
               'Ártico',
               'B',
               None),
              ('Qual cidade é famosa pelo Cristo Redentor?',
               'Lisboa',
               'Rio de Janeiro',
               'Buenos Aires',
               'São Paulo',
               'B',
               None),
              ('Qual é a unidade básica da vida?',
               'Átomo',
               'Célula',
               'Molécula',
               'Tecido',
               'B',
               None),
              ('Qual gás é essencial para a respiração humana?',
               'Nitrogênio',
               'Gás Carbônico',
               'Hélio',
               'Oxigênio',
               'D',
               None),
              ('Qual país tem mais vulcões ativos?',
               'Indonésia',
               'Japão',
               'Islândia',
               'Itália',
               'A',
               None),
              ('Qual deserto é o maior (não polar)?',
               'Saara',
               'Kalahari',
               'Gobi',
               'Atacama',
               'A',
               None),
              ('Qual instrumento mede a pressão atmosférica?',
               'Barômetro',
               'Termômetro',
               'Higrômetro',
               'Anemômetro',
               'A',
               None),
              ('Qual é o principal gás do efeito estufa dos fósseis?',
               'O₂',
               'N₂',
               'CH₄',
               'CO₂',
               'D',
               None),
              ("Quem pintou 'A Noite Estrelada'?",
               'Van Gogh',
               'Monet',
               'Picasso',
               'Dalí',
               'A',
               None),
              ('Qual país venceu a Copa do Mundo feminina de 2019?',
               'Estados Unidos',
               'Holanda',
               'Alemanha',
               'Inglaterra',
               'A',
               None),
              ('Qual idioma é mais falado como nativo?',
               'Inglês',
               'Hindi',
               'Espanhol',
               'Mandarim',
               'D',
               None),
              ("Qual cidade é conhecida como 'A Cidade Luz'?",
               'Londres',
               'Roma',
               'Berlim',
               'Paris',
               'D',
               None),
              ('Qual é o símbolo químico da água?', 'H2', 'O2', 'CO2', 'H2O', 'D', None),
              ('Qual montanha é a mais alta do mundo?',
               'K2',
               'Kangchenjunga',
               'Lhotse',
               'Everest',
               'D',
               None),
              ('Qual continente tem o maior número de países?',
               'Ásia',
               'Europa',
               'África',
               'América',
               'C',
               None),
              ("Qual escritor criou 'Dom Quixote'?",
               'Victor Hugo',
               'Goethe',
               'Shakespeare',
               'Miguel de Cervantes',
               'D',
               None),
              ('Qual é o instrumento usado para medir temperatura?',
               'Higrômetro',
               'Barômetro',
               'Termômetro',
               'Anemômetro',
               'C',
               None),
              ('Qual é o símbolo químico do ouro?', 'Ag', 'Fe', 'Au', 'Cu', 'C', None),
              ('Qual cidade abriga o Coliseu?',
               'Atenas',
               'Istambul',
               'Roma',
               'Florença',
               'C',
               None),
              ('Qual é a moeda do Japão?', 'Yuan', 'Won', 'Iene (Yen)', 'Baht', 'C', None),
              ('Qual país tem a cidade de Marrakech?',
               'Egito',
               'Tunísia',
               'Marrocos',
               'Argélia',
               'C',
               None),
              ('Qual é o menor país do mundo?',
               'Mônaco',
               'San Marino',
               'Vaticano',
               'Liechtenstein',
               'C',
               None)],
 'Esportes': [('Quem é o atleta na imagem (multicampeão dos 100m e 200m)?',
               'Justin Gatlin',
               'Yohan Blake',
               'Asafa Powell',
               'Usain Bolt',
               'D',
               '/static/img/bolt.jpg'),
              ('Qual piloto aparece na imagem, heptacampeão da F1?',
               'Lewis Hamilton',
               'Sebastian Vettel',
               'Fernando Alonso',
               'Nico Rosberg',
               'A',
               '/static/img/hamilton.jpg'),
              ('A taça sobre a grama na imagem é de qual torneio?',
               'Roland Garros',
               'Australian Open',
               'Wimbledon',
               'US Open',
               'C',
               '/static/img/wimbledon.jpg'),
              ('Qual país sediou as Olimpíadas de 2008?',
               'Japão',
               'Brasil',
               'China',
               'Rússia',
               'C',
               None),
              ('Qual seleção venceu a primeira Copa do Mundo (1930)?',
               'Argentina',
               'Brasil',
               'Itália',
               'Uruguai',
               'D',
               None),
              ("Quem marcou o 'Gol da Mão de Deus' em 1986?",
               'Platini',
               'Maradona',
               'Lineker',
               'Zico',
               'B',
               None),
              ('Qual clube revelou Pelé para o mundo?',
               'Corinthians',
               'Santos',
               'Flamengo',
               'Vasco',
               'B',
               None),
              ('Qual é o torneio anual de clubes mais antigo do futebol?',
               'FA Cup',
               'Copa do Rei',
               'Taça de Portugal',
               'DFB-Pokal',
               'A',
               None),
              ('Qual seleção venceu a Copa do Mundo de 2010?',
               'Alemanha',
               'Espanha',
               'Holanda',
               'Uruguai',
               'B',
               None),
              ('Em qual cidade ocorre a maratona mais antiga em continuidade?',
               'Boston',
               'Londres',
               'Berlim',
               'Atenas',
               'A',
               None),
              ('Quem é o maior medalhista olímpico da história?',
               'Michael Phelps',
               'Usain Bolt',
               'Larisa Latynina',
               'Mark Spitz',
               'A',
               None),
              ("Qual tenista conquistou o 'Golden Slam' no mesmo ano?",
               'Serena Williams',
               'Steffi Graf',
               'Martina Navratilova',
               'Monica Seles',
               'B',
               None),
              ('Qual seleção masculina ganhou o primeiro ouro olímpico do vôlei brasileiro?',
               'Brasil (1992)',
               'Brasil (2004)',
               'Brasil (2008)',
               'Brasil (2016)',
               'A',
               None),
              ('Qual equipe foi campeã da NBA em 2016 após virada histórica?',
               'Golden State Warriors',
               'Cleveland Cavaliers',
               'San Antonio Spurs',
               'Miami Heat',
               'B',
               None),
              ('Em qual cidade foi fundada a FIFA (1904)?',
               'Zurique',
               'Paris',
               'Berlim',
               'Genebra',
               'B',
               None),
              ('Qual clube venceu a primeira Libertadores (1960)?',
               'Peñarol',
               'Independiente',
               'Santos',
               'Boca Juniors',
               'A',
               None),
              ('Que país tem mais títulos da Copa do Mundo?',
               'Alemanha',
               'Itália',
               'Brasil',
               'Argentina',
               'C',
               None),
              ("Quem é o 'Fenômeno' do futebol?",
               'Romário',
               'Ronaldo',
               'Ronaldinho',
               'Rivaldo',
               'B',
               None),
              ('Qual Grand Slam é disputado em piso de saibro?',
               'Wimbledon',
               'Roland Garros',
               'US Open',
               'Australian Open',
               'B',
               None),
              ("Quem é conhecido como 'O Rei' no basquete?",
               'LeBron James',
               'Kobe Bryant',
               'Michael Jordan',
               'Magic Johnson',
               'C',
               None),
              ('Qual seleção venceu a Copa do Mundo de 1998?',
               'Brasil',
               'França',
               'Alemanha',
               'Itália',
               'B',
               None),
              ('Em que país nasceu Ayrton Senna?',
               'Argentina',
               'Portugal',
               'Espanha',
               'Brasil',
               'D',
               None),
              ('Quantos pontos vale uma cesta de três no basquete?', '1', '2', '3', '4', 'C', None),
              ('Quem foi campeão da Copa América 2019?',
               'Argentina',
               'Chile',
               'Uruguai',
               'Brasil',
               'D',
               None),
              ("Em qual cidade ocorreu a 'Mão de Deus' (1986)?",
               'Cidade do México',
               'Guadalajara',
               'Monterrey',
               'León',
               'A',
               None),
              ('Qual país conquistou o 1º Mundial de Clubes da FIFA (2000)?',
               'Real Madrid',
               'Boca Juniors',
               'Manchester United',
               'Corinthians',
               'D',
               None),
              ('Qual esporte tem Grand Prix e escuderias?',
               'Motocross',
               'Rali',
               'NASCAR',
               'Fórmula 1',
               'D',
               None),
              ("Qual seleção é conhecida como 'La Roja'?",
               'Chile',
               'Portugal',
               'Espanha',
               'Suíça',
               'C',
               None),
              ('Qual torneio de tênis abre a temporada dos Grand Slams?',
               'Roland Garros',
               'Wimbledon',
               'US Open',
               'Australian Open',
               'D',
               None),
              ("Qual clube tem o apelido 'Rubro-Negro' no Brasil?",
               'Palmeiras',
               'Grêmio',
               'Flamengo',
               'Santos',
               'C',
               None)],
 'História': [('O que a imagem simboliza (evento de 1989 na Europa)?',
               'Primavera de Praga',
               'Tratado de Maastricht',
               'Queda do Muro de Berlim',
               'Reunificação Alemã',
               'C',
               '/static/img/muro.jpg'),
              ('Quem é o conquistador na imagem (fundou império até a Índia)?',
               'Júlio César',
               'Alexandre, o Grande',
               'Ciro, o Grande',
               'Aníbal',
               'B',
               '/static/img/alexandre.jpg'),
              ('A estátua na imagem representa qual império clássico?',
               'Império Bizantino',
               'Império Romano',
               'Império Persa',
               'Império Otomano',
               'B',
               '/static/img/cesar.jpg'),
              ('Em que ano terminou a Segunda Guerra Mundial?',
               '1944',
               '1945',
               '1946',
               '1947',
               'B',
               None),
              ('Quem proclamou a Independência do Brasil?',
               'Dom Pedro I',
               'José Bonifácio',
               'Marechal Deodoro',
               'Tiradentes',
               'A',
               None),
              ('Qual civilização construiu Machu Picchu?',
               'Maia',
               'Inca',
               'Asteca',
               'Olmeca',
               'B',
               None),
              ('Qual revolução marcou 1789 na França?',
               'Industrial',
               'Gloriosa',
               'Francesa',
               'Russa',
               'C',
               None),
              ('Quem foi derrotado em Waterloo (1815)?',
               'Napoleão Bonaparte',
               'Luís XIV',
               'Carlos Magno',
               'Robespierre',
               'A',
               None),
              ('Qual tratado encerrou a Primeira Guerra Mundial?',
               'Tordesilhas',
               'Versalhes',
               'Utrecht',
               'Paris (1763)',
               'B',
               None),
              ('Quem foi o primeiro presidente do Brasil?',
               'Marechal Deodoro da Fonseca',
               'Floriano Peixoto',
               'Campos Sales',
               'Prudente de Morais',
               'A',
               None),
              ('Qual império tinha Constantinopla como capital?',
               'Carolíngio',
               'Bizantino',
               'Romano do Ocidente',
               'Sacro Império Romano',
               'B',
               None),
              ('Quem liderou a Marcha do Sal (1930) na Índia?',
               'Nehru',
               'Gandhi',
               'Jinnah',
               'Tagore',
               'B',
               None),
              ('Qual império conquistou Tenochtitlán em 1521?',
               'Português',
               'Espanhol',
               'Inglês',
               'Holandês',
               'B',
               None),
              ('Qual pandemia assolou a Europa no século XIV?',
               'Gripe Espanhola',
               'Cólera',
               'Varíola',
               'Peste Negra',
               'D',
               None),
              ('Quem foi a monarca inglesa da era vitoriana?',
               'Elizabeth I',
               'Mary I',
               'Anne',
               'Victoria',
               'D',
               None),
              ('Qual cidade foi bombardeada por armas nucleares (uma delas) em 1945?',
               'Tóquio',
               'Osaka',
               'Kyoto',
               'Hiroshima',
               'D',
               None),
              ('Qual rota conectou por séculos Oriente e Ocidente?',
               'Rota do Âmbar',
               'Rota do Ouro',
               'Via Ápia',
               'Rota da Seda',
               'D',
               None),
              ('Qual navegação europeia chegou ao Brasil em 1500?',
               'Vasco da Gama',
               'Cristóvão Colombo',
               'Amerigo Vespucci',
               'Pedro Álvares Cabral',
               'D',
               None),
              ('Que império caiu em 476 d.C., marcando o fim da Antiguidade?',
               'Romano do Ocidente',
               'Bizantino',
               'Persa',
               'Otomano',
               'A',
               None),
              ('Quem foi o líder negro dos EUA que defendeu a não-violência?',
               'Malcolm X',
               'Frederick Douglass',
               'Rosa Parks',
               'Martin Luther King Jr.',
               'D',
               None),
              ('Qual foi a principal guerra do século XVII que devastou a Europa Central?',
               'Guerra dos Trinta Anos',
               'Guerra dos Sete Anos',
               'Guerra Civil Inglesa',
               'Guerra de Sucessão Espanhola',
               'A',
               None),
              ('Qual cidade-estado foi o berço da democracia direta?',
               'Esparta',
               'Roma',
               'Corinto',
               'Atenas',
               'D',
               None),
              ("Quem escreveu 'O Príncipe' (1532)?",
               'Maquiavel',
               'Erasmo',
               'Montesquieu',
               'Rousseau',
               'A',
               None),
              ('Qual foi a primeira civilização a desenvolver escrita cuneiforme?',
               'Egípcia',
               'Fenícia',
               'Suméria',
               'Persa',
               'C',
               None),
              ('Qual foi a exploração que contornou a África até a Índia (1497–1499)?',
               'Colombo',
               'Magalhães',
               'Vasco da Gama',
               'Cabral',
               'C',
               None),
              ('Qual reforma religiosa foi iniciada por Martinho Lutero?',
               'Contrarreforma',
               'Grande Cisma',
               'Reforma Protestante',
               'Anglicanismo',
               'C',
               None),
              ('Qual império dominou a Península Ibérica por séculos como Al-Andalus?',
               'Romano',
               'Visigodo',
               'Mouro',
               'Celta',
               'C',
               None),
              ('Qual navegação deu a volta ao mundo pela primeira vez?',
               'Magalhães-Elcano',
               'Colombo',
               'Vasco da Gama',
               'Cook',
               'A',
               None),
              ('Quem unificou a Alemanha em 1871 como chanceler?',
               'Kaiser Wilhelm II',
               'Frederico o Grande',
               'Bismarck',
               'Ludwig II',
               'C',
               None),
              ('Qual revolução derrubou o czarismo em 1917?',
               'Revolução Chinesa',
               'Revolução Cubana',
               'Revolução Russa',
               'Revolução Mexicana',
               'C',
               None)],
 'Jogos': [('Qual herói aparece na imagem (franquia da Nintendo com espada)?',
            'Zelda',
            'Ganondorf',
            'Link',
            'Pit',
            'C',
            '/static/img/link.jpg'),
           ('Qual jogo é mostrado na capa (sandbox de 2013)?',
            'GTA IV',
            'GTA V',
            'Sleeping Dogs',
            'Mafia II',
            'B',
            '/static/img/gta5.jpg'),
           ('Qual jogo de blocos em mundo aberto aparece na imagem?',
            'Roblox',
            'Terraria',
            "No Man's Sky",
            'Minecraft',
            'D',
            '/static/img/minecraft.jpg'),
           ('Qual é o nome do irmão do Mario?', 'Wario', 'Luigi', 'Yoshi', 'Toad', 'B', None),
           ('Em que ano foi lançado o primeiro PlayStation?',
            '1993',
            '1994',
            '1995',
            '1996',
            'B',
            None),
           ('Quem criou o conceito original de Tetris?',
            'Hideo Kojima',
            'Shigeru Miyamoto',
            'Alexey Pajitnov',
            'Sid Meier',
            'C',
            None),
           ('Em qual franquia surgiu Master Chief?',
            'Gears of War',
            'Destiny',
            'Halo',
            'Doom',
            'C',
            None),
           ("Qual jogo de luta popularizou 'Finish Him!'?",
            'Tekken',
            'Mortal Kombat',
            'Killer Instinct',
            'Street Fighter',
            'B',
            None),
           ("Qual console recebeu 'Ocarina of Time' originalmente?",
            'GameCube',
            'SNES',
            'Nintendo 64',
            'Wii',
            'C',
            None),
           ("Qual estúdio criou 'The Witcher 3'?",
            'CD Projekt Red',
            'Bethesda',
            'BioWare',
            'Obsidian',
            'A',
            None),
           ('Qual jogo popularizou o battle royale em 2017?',
            'Fortnite',
            'H1Z1',
            'PUBG',
            'Apex Legends',
            'C',
            None),
           ("Qual desenvolvedora criou 'Dark Souls'?",
            'FromSoftware',
            'Capcom',
            'Konami',
            'Square Enix',
            'A',
            None),
           ('Em qual jogo a cidade de Raccoon City é cenário?',
            'Dead Space',
            'Resident Evil',
            'Silent Hill',
            'The Last of Us',
            'B',
            None),
           ('Qual personagem coleta anéis em velocidade supersônica?',
            'Crash',
            'Sonic',
            'Spyro',
            'Rayman',
            'B',
            None),
           ("Quem produz a série 'Gran Turismo'?",
            'Turn 10',
            'Polyphony Digital',
            'Codemasters',
            'EA Canada',
            'B',
            None),
           ('Qual indie de 2015 explora o fundo do mar e o luto?',
            'Abzû',
            'Journey',
            'Firewatch',
            'Inside',
            'A',
            None),
           ('Qual heroína usa o traje Power Suit?',
            'Bayonetta',
            'Samus Aran',
            'Jill Valentine',
            'Aloy',
            'B',
            None),
           ("Qual jogo popularizou o inimigo 'creeper'?",
            "Don't Starve",
            'Terraria',
            'Minecraft',
            'Subnautica',
            'C',
            None),
           ('Em qual série aparece a cidade submersa Rapture (DLC/coleções)?',
            'Dishonored',
            'Prey',
            'Deus Ex',
            'Bioshock',
            'D',
            None),
           ('Qual franquia da Nintendo apresenta Hyrule?',
            'Metroid',
            'Kirby',
            'Zelda',
            'Star Fox',
            'C',
            None),
           ('Quem é o encanador rival amarelo do Mario?',
            'Wario',
            'Waluigi',
            'Toad',
            'Bowser',
            'A',
            None),
           ("Qual jogo tem o modo 'Creative' amplamente usado para construir?",
            'Minecraft',
            'Roblox',
            'The Sims',
            'Cities: Skylines',
            'A',
            None),
           ('Qual empresa lançou o console Dreamcast?',
            'Sega',
            'Nintendo',
            'Sony',
            'Atari',
            'A',
            None),
           ("Qual é o subtítulo do jogo 'Zelda: BOTW'?",
            'Breath of the Wild',
            'Tears of the Kingdom',
            'A Link Between Worlds',
            'Skyward Sword',
            'A',
            None),
           ('Qual jogo da Rockstar se passa no Velho Oeste?',
            'Max Payne',
            'Bully',
            'L.A. Noire',
            'Red Dead Redemption',
            'D',
            None),
           ("Qual plataforma recebeu 'Half-Life 2' no lançamento?",
            'PS2',
            'PS3',
            'Xbox One',
            'PC',
            'D',
            None),
           ('Qual jogo tem as classes Scout, Heavy e Medic?',
            'Overwatch',
            'Valorant',
            'Paladins',
            'Team Fortress 2',
            'D',
            None),
           ('Qual série tem o personagem Geralt de Rívia?',
            'The Elder Scrolls',
            'Dragon Age',
            'Fable',
            'The Witcher',
            'D',
            None),
           ("Qual é o antagonista principal de 'The Legend of Zelda' clássico?",
            'Ridley',
            'Bowser',
            'Ganondorf',
            'Giygas',
            'C',
            None),
           ("Qual jogo de 2016 popularizou o termo 'Battle Royale' gratuito?",
            'PUBG',
            'Apex Legends',
            'Warzone',
            'Fortnite',
            'D',
            None)],
 'Lógica': [('A figura mostra um sólido com 6 faces quadradas. Qual é?',
             'Cilindro',
             'Prisma triangular',
             'Cubo',
             'Esfera',
             'C',
             '/static/img/cubo.jpg'),
            ('A imagem mostra uma curva fechada sem vértices. Que forma é?',
             'Círculo',
             'Elipse',
             'Parábola',
             'Hipérbole',
             'A',
             '/static/img/circle.jpg'),
            ('Que polígono está na imagem (5 lados)?',
             'Hexágono',
             'Pentágono',
             'Heptágono',
             'Quadrilátero',
             'B',
             '/static/img/pentagon.jpg'),
            ('Complete: 3, 6, 12, 24, …', '36', '42', '48', '54', 'C', None),
            ('Se 5 máquinas fazem 5 peças em 5 minutos, 100 máquinas fazem 100 peças em…',
             '5',
             '50',
             '100',
             '500',
             'A',
             None),
            ('Todos os mamíferos respiram. Baleias respiram. Logo…',
             'Baleias não são mamíferos',
             'Baleias são mamíferos',
             'Baleias não respiram',
             'Nenhuma das anteriores',
             'B',
             None),
            ('Qual número falta? 1, 1, 2, 3, 5, 8, …', '10', '11', '12', '13', 'D', None),
            ('Se todo A é B e todo B é C, então…',
             'Todo A é C',
             'Nenhum A é C',
             'Alguns A não são C',
             'Não é possível concluir',
             'A',
             None),
            ('Qual próxima figura lógica: ▲, ■, ▲, ■, …', '■', '▲', '○', '◆', 'B', None),
            ("Em um grupo, todos são honestos ou mentirosos. Se alguém diz 'sou mentiroso', então…",
             'É honesto',
             'É mentiroso',
             'É contraditório',
             'Impossível determinar',
             'C',
             None),
            ('Se hoje é terça e faltam 10 dias para o evento, será…',
             'Sexta',
             'Sábado',
             'Domingo',
             'Segunda',
             'C',
             None),
            ('Menor número positivo divisível por 3, 4 e 5?', '30', '60', '120', '15', 'A', None),
            ('Um trem percorre 300 km em 3h. Velocidade média?',
             '80 km/h',
             '90 km/h',
             '100 km/h',
             '110 km/h',
             'C',
             None),
            ("Negação de 'A ou B' é verdadeira. Então…",
             'A e B verdadeiros',
             'A e B falsos',
             'Pelo menos A verdadeiro',
             'Exatamente um verdadeiro',
             'B',
             None),
            ('Próximo primo: 2, 3, 5, 7, 11, …', '12', '13', '14', '15', 'B', None),
            ('Soma interna 540° pertence a…',
             'Pentágono',
             'Hexágono',
             'Heptágono',
             'Octógono',
             'A',
             None),
            ('Se 20% de x é 50, x é…', '200', '220', '240', '250', 'D', None),
            ('Área de um retângulo 5x9?', '35', '40', '45', '54', 'C', None),
            ('Se P ⇒ Q é falso, então…',
             'P verdadeiro e Q falso',
             'P falso e Q verdadeiro',
             'Ambos verdadeiros',
             'Ambos falsos',
             'A',
             None),
            ('Se três números somam 60 e dois são 15 e 23, o terceiro é…',
             '22',
             '21',
             '20',
             '19',
             'C',
             None),
            ('Se 8 é 2³, então 32 é…', '2⁴', '2⁵', '2⁶', '2⁷', 'B', None),
            ('Se x + x/2 = 18, então x é…', '10', '11', '12', '14', 'C', None),
            ('Qual é a mediana de 2, 3, 9, 11, 15?', '9', '11', '3', '7', 'A', None),
            ('Qual é a moda de 1, 2, 2, 3, 4?', '1', '2', '3', '4', 'B', None),
            ('Se hoje é o 3º dia do mês e daqui 30 dias será o…',
             '2º',
             '4º',
             '5º',
             '3º de novo',
             'D',
             None),
            ('Se um ângulo agudo é menor que 90°, 47° é…',
             'Reto',
             'Obtuso',
             'Raso',
             'Agudo',
             'D',
             None),
            ('Se o dobro de y é 18, então y é…', '7', '8', '10', '9', 'D', None),
            ('Na sequência 1,4,9,16,… o próximo é…', '20', '24', '26', '25', 'D', None),
            ('Qual fração é equivalente a 0,5?', '1/3', '1/2', '2/3', '3/4', 'B', None),
            ('Se 3x = 27, então x é…', '6', '7', '8', '9', 'D', None)],
 'Música': [('Qual banda aparece na imagem (quarteto britânico com Freddie Mercury)?',
             'The Beatles',
             'Queen',
             'Pink Floyd',
             'The Who',
             'B',
             '/static/img/queen.jpg'),
            ('Quem é o artista na imagem (álbum entre os mais vendidos da história)?',
             'Prince',
             'Michael Jackson',
             'Stevie Wonder',
             'Lionel Richie',
             'B',
             '/static/img/mj.jpg'),
            ("Quem é a cantora na imagem (conhecida por 'Hello' e 'Rolling in the Deep')?",
             'Lady Gaga',
             'Adele',
             'Beyoncé',
             'Rihanna',
             'B',
             '/static/img/adele.jpg'),
            ('Quem foi o baterista dos Beatles?',
             'Ringo Starr',
             'John Bonham',
             'Phil Collins',
             'Charlie Watts',
             'A',
             None),
            ("Qual banda lançou 'The Dark Side of the Moon'?",
             'Pink Floyd',
             'Led Zeppelin',
             'The Doors',
             'Queen',
             'A',
             None),
            ("Quem é conhecido como o 'Rei do Rock'?",
             'Elvis Presley',
             'Chuck Berry',
             'Jerry Lee Lewis',
             'Buddy Holly',
             'A',
             None),
            ("Qual rapper lançou 'To Pimp a Butterfly'?",
             'Kendrick Lamar',
             'Kanye West',
             'J. Cole',
             'Drake',
             'A',
             None),
            ("Qual cantora lançou o álbum 'Lemonade'?",
             'Rihanna',
             'Beyoncé',
             'Adele',
             'Alicia Keys',
             'B',
             None),
            ("Qual banda grunge popularizou 'Nevermind'?",
             'Pearl Jam',
             'Nirvana',
             'Soundgarden',
             'Alice in Chains',
             'B',
             None),
            ('Qual compositor ficou completamente surdo no fim da vida?',
             'Mozart',
             'Beethoven',
             'Bach',
             'Tchaikovsky',
             'B',
             None),
            ('Quem é o baixista/vocalista do Rush?',
             'Alex Lifeson',
             'Geddy Lee',
             'Neil Peart',
             'John Entwistle',
             'B',
             None),
            ('Qual movimento surgiu no Bronx nos anos 70?',
             'Disco',
             'Hip hop',
             'Punk',
             'New Wave',
             'B',
             None),
            ("Quem é a 'Rainha do Fado'?",
             'Mariza',
             'Dulce Pontes',
             'Carminho',
             'Amália Rodrigues',
             'D',
             None),
            ("Qual banda lançou 'Californication'?",
             'Green Day',
             'The Strokes',
             'Foo Fighters',
             'Red Hot Chili Peppers',
             'D',
             None),
            ("Quem cantou 'Bad Guy'?", 'Billie Eilish', 'Dua Lipa', 'Lorde', 'Halsey', 'A', None),
            ('Qual guitarrista incendiou a guitarra em Monterey (1967)?',
             'Eric Clapton',
             'Pete Townshend',
             'Jimmy Page',
             'Jimi Hendrix',
             'D',
             None),
            ('Qual gênero é associado ao acordeon no Nordeste brasileiro?',
             'Bossa Nova',
             'Frevo',
             'Samba',
             'Forró',
             'D',
             None),
            ('Qual produtor é creditado por popularizar o G-funk?',
             'Dr. Dre',
             'Snoop Dogg',
             'Ice Cube',
             'Pharrell Williams',
             'A',
             None),
            ("Qual é a voz de 'Rolling in the Deep'?",
             'Beyoncé',
             'Amy Winehouse',
             'Alicia Keys',
             'Adele',
             'D',
             None),
            ("Qual banda é do álbum 'OK Computer'?",
             'Radiohead',
             'U2',
             'Coldplay',
             'Oasis',
             'A',
             None),
            ("Qual cantor brasileiro lançou 'Nada Como um Dia…'?",
             'Raimundos',
             'Charlie Brown Jr.',
             'Titãs',
             "Racionais MC's",
             'D',
             None),
            ('Qual é o instrumento principal de John Coltrane?',
             'Trompete',
             'Piano',
             'Saxofone',
             'Contrabaixo',
             'C',
             None),
            ("Qual cantora pop lançou 'Future Nostalgia'?",
             'Katy Perry',
             'Ariana Grande',
             'Dua Lipa',
             'Selena Gomez',
             'C',
             None),
            ('Quem é o guitarrista do Queen?',
             'Jimmy Page',
             'Angus Young',
             'Brian May',
             'Slash',
             'C',
             None),
            ("Qual banda tem o hit 'Bohemian Rhapsody'?",
             'The Beatles',
             'ABBA',
             'Queen',
             'Bee Gees',
             'C',
             None),
            ('Qual é o verdadeiro nome de Lady Gaga?',
             'Robyn Fenty',
             'Alecia Moore',
             'Stefani Germanotta',
             'Katheryn Hudson',
             'C',
             None),
            ("Qual dupla brasileira lançou 'Domingo de Manhã'?",
             'Jorge & Mateus',
             'Zé Neto & Cristiano',
             'Marcos & Belutti',
             'Henrique & Juliano',
             'C',
             None),
            ("Qual artista é famoso por 'Purple Rain'?",
             'Michael Jackson',
             'George Michael',
             'Prince',
             'Lionel Richie',
             'C',
             None),
            ("Qual banda britânica tem o álbum 'A Night at the Opera'?",
             'The Beatles',
             'The Who',
             'Queen',
             'Pink Floyd',
             'C',
             None),
            ("Qual banda britânica lançou o álbum 'The Bends'?",
             'Oasis',
             'Blur',
             'Coldplay',
             'Radiohead',
             'D',
             None)],
 'TV/Cinema': [('Quem é a atriz na imagem (interpretou Daenerys Targaryen)?',
                'Sophie Turner',
                'Emilia Clarke',
                'Natalie Dormer',
                'Lena Headey',
                'B',
                '/static/img/emilia.jpg'),
               ('Qual filme é mostrado no pôster (óculos e código verde)?',
                'Minority Report',
                'Blade Runner',
                'Matrix',
                'Tron',
                'C',
                '/static/img/matrix.jpg'),
               ('Quem aparece caracterizado como pirata na imagem?',
                'Johnny Depp',
                'Orlando Bloom',
                'Geoffrey Rush',
                'Tom Hardy',
                'A',
                '/static/img/jack.jpg'),
               ("Em qual cidade se passa a maior parte de 'Friends'?",
                'Nova York',
                'Los Angeles',
                'Chicago',
                'Boston',
                'A',
                None),
               ("Quem dirigiu 'Jurassic Park' (1993)?",
                'Steven Spielberg',
                'James Cameron',
                'Ridley Scott',
                'George Lucas',
                'A',
                None),
               ('Quem interpretou Wolverine na maior parte da franquia X-Men?',
                'Hugh Jackman',
                'Christian Bale',
                'Robert Downey Jr.',
                'Chris Hemsworth',
                'A',
                None),
               ("Qual vilão clássico revela ser pai em 'O Império Contra-Ataca'?",
                'Darth Vader',
                'Kylo Ren',
                'Darth Maul',
                'General Grievous',
                'A',
                None),
               ('Qual filme ganhou o Oscar de Melhor Filme em 2020?',
                '1917',
                'Coringa',
                'Parasita',
                'Era uma Vez em… Hollywood',
                'C',
                None),
               ('Qual série se passa na fictícia Hawkins, nos anos 80?',
                'Stranger Things',
                'Dark',
                'The OA',
                'Black Mirror',
                'A',
                None),
               ("Quem dirigiu 'A Origem' (Inception)?",
                'Christopher Nolan',
                'Sam Mendes',
                'Guy Ritchie',
                'David Fincher',
                'A',
                None),
               ('Qual trilogia apresenta Mordor e o Um Anel?',
                'Harry Potter',
                'O Senhor dos Anéis',
                'Nárnia',
                'Percy Jackson',
                'B',
                None),
               ("Qual é o nome do universo compartilhado da Marvel no cinema?", "DCU", "MCU", "DCEU", "FoxVerse", "B", None),
               ('Qual animação da Pixar personifica emoções?',
                'Soul',
                'Viva',
                'Up',
                'Divertida Mente',
                'D',
                None),
               ('Quem dublou Buzz Lightyear (versão original)?',
                'Tom Hanks',
                'Tim Allen',
                'Robin Williams',
                'Jim Carrey',
                'B',
                None),
               ("Qual diretor assinou 'La La Land'?",
                'Baz Luhrmann',
                'Greta Gerwig',
                'Richard Linklater',
                'Damien Chazelle',
                'D',
                None),
               ('Qual filme de 2015 trouxe de volta Max e Furiosa?',
                'Sicario',
                'The Revenant',
                'Mad Max: Estrada da Fúria',
                'Ex Machina',
                'C',
                None),
               ('Qual série medieval da HBO tem a Casa Stark?',
                'Vikings',
                'Game of Thrones',
                'The Witcher',
                'The Last Kingdom',
                'B',
                None),
               ("Em qual filme ouvimos 'Run, Forrest, run!'?",
                'The Shawshank Redemption',
                'Pulp Fiction',
                'Se7en',
                'Forrest Gump',
                'D',
                None),
               ("Quem interpreta Eleven em 'Stranger Things'?",
                'Natalia Dyer',
                'Sadie Sink',
                'Winona Ryder',
                'Millie Bobby Brown',
                'D',
                None),
               ('Qual animador/estúdio criou Mickey Mouse?',
                'Hanna-Barbera',
                'DreamWorks',
                'Illumination',
                'Walt Disney',
                'D',
                None),
               ("Qual filme de 1999 popularizou o 'bullet time'?",
                'Clube da Luta',
                'Beleza Americana',
                'O Sexto Sentido',
                'Matrix',
                'D',
                None),
               ("Quem dirigiu 'Blade Runner 2049'?",
                'Ridley Scott',
                'Neill Blomkamp',
                'Denis Villeneuve',
                'Alex Garland',
                'C',
                None),
               ('Qual série policial acompanha um professor de química e seu ex-aluno?',
                'Better Call Saul',
                'Breaking Bad',
                'Narcos',
                'Ozark',
                'B',
                None),
               ('Qual filme ganhou Melhor Filme em 2019 (Academy Awards)?',
                'Roma',
                'Bohemian Rhapsody',
                'Green Book',
                'A Favorita',
                'C',
                None),
               ('Qual é o nome do brinquedo cowboy em Toy Story?',
                'Buzz',
                'Woody',
                'Jessie',
                'Rex',
                'B',
                None),
               ("Qual diretor é conhecido por tramas complexas como 'Tenet'?",
                'Quentin Tarantino',
                'David Fincher',
                'Christopher Nolan',
                'Paul Thomas Anderson',
                'C',
                None),
               ('Em qual série o advogado Saul Goodman aparece inicialmente?',
                'Better Call Saul',
                'Breaking Bad',
                'Fargo',
                'Narcos',
                'B',
                None),
               ('Qual filme musical de 2016 tem números de dança em LA?',
                'The Greatest Showman',
                'A Star Is Born',
                'La La Land',
                'Into the Woods',
                'C',
                None),
               ('Qual saga espacial apresenta a família Skywalker?',
                'Star Trek',
                'Star Wars',
                'Duna',
                'Guardians of the Galaxy',
                'B',
                None),
               ("Qual cineasta dirigiu 'A Chegada' (Arrival)?",
                'Christopher Nolan',
                'James Cameron',
                'Denis Villeneuve',
                'Ron Howard',
                'C',
                None)]}


def main():
    Base.metadata.create_all(engine)
    db = SessionLocal()
    # Insere apenas se estiver vazio; ajuste se quiser 'completar' sem apagar o DB
    if db.query(Question).count() == 0:
        for theme, rows in SEED.items():
            random.shuffle(rows)  # embaralha questões do tema
            for (st, a, b, c, d, corr, img) in rows:
                db.add(Question(
                    theme=theme,
                    statement=st,
                    opt_a=a, opt_b=b, opt_c=c, opt_d=d,
                    correct=corr,
                    image_url=img
                ))
        db.commit()
    db.close()

if __name__ == "__main__":
    main()